<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'OfficeSuite' => 'Pacote Office',
    'Update: ' => 'Atualizar: ',
    'updated successfully.' => 'atualizado com sucesso',
    'Actions' => 'Ações',
    'Are you sure you want to delete this item?' => 'Tem certeza que deseja apagar este item?',
    'Create' => 'Criar',
    'Create Location' => 'Novo local',
    'Create Office Suite' => 'Novo pacote office',
    'Create Os' => 'Novo sist. oper.',
    'Delete' => 'Apagar',
    'Location' => 'Local',
    'Locations' => 'Locais',
    'Office Suites' => 'Pacotes Office',
    'Os' => 'Sist. Oper',
    'Reset' => 'Reiniciar',
    'Search' => 'Buscar',
    'Update' => 'Atualizar',
    'created successfully.' => 'criado com sucesso.',
];
