<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Smartphones' => '',
    'Switches' => '',
    'Asset Groups' => 'Grupos de ativos',
    'Authorization' => 'Autorização',
    'Create authorization rules' => 'Criar regras de autorização',
    'Dashboard' => 'Painel de indicadores',
    'Locations' => 'Locais',
    'Monitoring' => 'Monitoramento',
    'OS Licenses' => 'Licenças de SO',
    'OSes' => 'SO',
    'Office Suite Licenses' => 'Licenças de Office',
    'Office Suites' => 'Pacotes Office',
    'Reports' => 'Relatórios',
    'Servers' => 'Servidores',
    'Software Licenses' => 'Licenças de programas',
    'Softwares' => 'Programas',
    'User Management' => 'Gerência de usuários',
    'User Permissions' => 'Permissões de usuários',
    'Workstations' => 'Estações de trabalho',
];
