<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CALs' => '',
    'Description' => 'Descrição',
    'Group' => 'Grupo',
    'Groups' => 'Grupos',
    'Hostname' => '',
    'Activation key' => 'Chave de ativação',
    'Annotations' => 'Anotações',
    'Asset' => 'Ativo',
    'Brand' => 'Marca',
    'Brand and model' => 'Marca e modelo',
    'Created at' => 'Criado em',
    'Created by' => 'Criado por',
    'Date of purchase' => 'Data de aquisição',
    'Digital license' => 'Licença digital',
    'Firmware install date' => 'Data de instalação do firmware',
    'Firmware release date' => 'Data do firmware',
    'Firmware version' => 'Versão de firmware',
    'ID' => 'ID',
    'IMEI Number' => 'Número IMEI',
    'IP address' => 'Endereço IP',
    'IP/MAC address' => 'Endereço IP/MAC',
    'In use' => 'Em uso',
    'Location' => 'Local',
    'Location name' => 'Local',
    'MAC address' => 'Endereço MAC',
    'Model' => 'Modelo',
    'Name' => 'Nome',
    'OS' => 'SO',
    'OS license' => 'Licença do SO',
    'OS version' => 'Versão do SO',
    'Office Suite' => 'Pacote Office',
    'Office Suite license' => 'Licença do Pacote Office',
    'Password' => 'Senha',
    'Ports' => 'portas',
    'Purchased licenses' => 'Licenças adquiridas',
    'Room' => 'Sala',
    'Serial number' => 'Número de série',
    'Service tag' => 'Etiqueta de serviço',
    'Software' => 'Programa',
    'Software license' => 'Licença do programa',
    'Updated at' => 'Atualizado em',
    'Updated by' => 'Atualizado por',
    'Usage' => 'Utilização',
    'User' => 'Usuário',
    'Username' => 'Nome de usuário',
    'key' => 'chave',
];
